### ISSUE TITLE
"An unexpected error has occurred." on loading playlists

### ISSUE THREAD

**Issue by Billy-Playz** [JMPerez/spotify-dedup#109]
Hi!
For around 2 days or so, when I log in to Spotify via my Facebook, it comes up with "An unexpected error has occurred."

I checked the console, and it comes up with the following:

> `⚠️ [Facebook Pixel] - You are sending a non-standard event 'dedup-user-logged-in'. The preferred way to send these events is using trackCustom. See 'https://developers.facebook.com/docs/ads-for-websites/pixel-events/#events' for more information. t @ fbevents.js:23`

> `⛔ DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ho (https://jmperezperez.com/spotify-dedup/_next/static/chunks/framework.ca3e7fa29692f350ed1d.js:1:99198)
    at ...`

Is there any fix to this?

**Comment by JMPerez** [comment]
I'm adding more debugging info on my end to try to detect this issue. Not sure what is producing it.

**Comment by JMPerez** [comment]
This has been fixed
