### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Kartikeya99** [JMPerez/spotify-dedup#117]
On clicking on the login with the Spotify button, it does authenticate however the view doesn't change to what it should when successfully authenticated.

**Comment by brianazick** [comment]
I see this issue as well, though I have been able to bypass it when accessing the site in MS Edge. I haven't been able to make it work in FireFox or Chrome, even with all extensions disabled.

**Comment by mvmisha** [comment]
Doesn't work on Edge too

**Comment by JMPerez** [comment]
@mvmisha please, try again. Looks like there was some change in a third party script that made the login fail.

**Comment by mvmisha** [comment]
@JMPerez yep, works fine now 👌

**Comment by JMPerez** [comment]
Closing this issue for now since the problem seems to be resolved. Feel free to reopen it if you can reproduce it again.
