### ISSUE TITLE
Dedup same song from different albums

### ISSUE THREAD

**Issue by taylor-peterson** [JMPerez/spotify-dedup#12]
It's pretty common to end up with duplicates of the same song with different Spotify URIs.

If possible, could you extend the tool to detect and remove songs with the same name, from the same artist, with (roughly) equivalent times?

**Comment by JMPerez** [comment]
@taylor-peterson Yes, this would definitely be a good addition. I will try to find some time to put this together.

**Comment by taylor-peterson** [comment]
That was quick and pruned a couple hundred tracks from my playlists - thanks!

One minor suggestion - you might want to have the duplication bubble include "artist" (e.g. same artist, name, and duration). When I first looked at the bubble, it wasn't clear that artist was included in the duplicate check.

**Comment by JMPerez** [comment]
Good point! I have just included artist to the badge, which I had forgotten.
