### ISSUE TITLE
Can't deduplicate some playlist

### ISSUE THREAD

**Issue by MrManchot** [JMPerez/spotify-dedup#14]
Hello,

I have a probleme. On some playlist the service work, but on some (seem to be when we have lot of doublon) nothing happened, and I have this Ajax error return :
`error: {status: 400, message: "Could not remove tracks, please check parameters."}`

Thank you for your job.
Regards

**Comment by JMPerez** [comment]
Could you pass me the id to one of the playlists that fails?

**Comment by MrManchot** [comment]
Here the link : 
spotify:user:mrmanchot:playlist:6NB5viBzVOHRYWXPZIZ3BY

**Comment by JMPerez** [comment]
@MrManchot Sorry for the delay. I was busy with other issues and forgot to check this one.

I see that the playlist doesn't have duplicates anymore, so I will close this ticket. Feel free to reopen it if you know how to reproduce it, or what set of tracks produces this bug.
