### ISSUE TITLE
Security Issues for Spotify

### ISSUE THREAD

**Issue by timbell86** [JMPerez/spotify-dedup#156]
Writing to ask if anyone else has been experiencing security issues with their Spotify account.
This is my 3rd password reset. On the previous password reset, I made a sophistic, generated password.
This is the only allowed app on my Spotify account, so I'm kind of like "What's going on?" at this point.

**Comment by JMPerez** [comment]
Hi,

Sad to hear. There hasn’t been any other report about this.

Apps using Spotify OAuth don’t have access to passwords and the whole login
flow (and password reset request) happens on Spotify’s domains. Thus,
password resets can be requested by inputting the username or email
address, either in Spotify’s login flow, which is always performed on their
site.

Not sure how to help out. Maybe Spotify can provide more info about where
the login request was originated from, which could help understand where
this person is trying to log in.

**Comment by JMPerez** [comment]
Closing the issue as Spotify Dedup is secure and doesn’t have access to passwords.
