### ISSUE TITLE
403s on Delete request

### ISSUE THREAD

**Issue by brrusselburg** [JMPerez/spotify-dedup#157]
This tool has worked perfectly for me before, so I'm wondering if something changed with Spotify's API recently?

I'm able to log in just fine. Here's a screenshot example of my listed dupes:
<img width="839" alt="Screenshot 2024-05-02 at 3 31 17 PM" src="https://github.com/JMPerez/spotify-dedup/assets/25828824/049116c3-f333-4fbf-ad18-57c0d7b5cc19">

When I click "Remove duplicates", however, nothing happens. I popped open the network tab in my browser console and:
<img width="1158" alt="Screenshot 2024-05-02 at 3 32 42 PM" src="https://github.com/JMPerez/spotify-dedup/assets/25828824/03a0cce0-cd80-43eb-a1a0-e7ca6716122d">

... I get a 403 / Forbidden response, which seems odd since I've already authenticated. Must be an issue with editing/creating and not simply fetching data? Wanted to give a heads up. Thanks!

EDIT: If it matters, I'm on a Mac M1 using Firefox

**Comment by JMPerez** [comment]
Thanks, @brrusselburg. I just noticed it :(

Spotify has changed the endpoint URL to remove tracks from a playlist, but the new endpoint doesn't support specifying what positions the track should be removed from. Thus, they end up removing all instances of the track.

* https://community.spotify.com/t5/Spotify-for-Developers/Positions-field-in-JSON-body-is-ignored-when-removing-tracks/m-p/6044424#M13702
* https://github.com/jwilsson/spotify-web-api-php/issues/271#issuecomment-2091524820
 
I'm trying to contact them, but they haven't been very active lately on forums nor twitter, so I have low expectations. Worst case scenario there is a workaround, where I delete the track and its duplicates, and then I add it back once, but that will change the position in the list.

**Comment by JMPerez** [comment]
More info about the issue on https://buymeacoffee.com/jmp/dedup-spotify-breaking-changes-api

**Comment by brrusselburg** [comment]
Agh, bummer. Thanks for all the info! 🤞

**Comment by JMPerez** [comment]
@brrusselburg  The tool should be fixed now and be able to remove duplicates in playlists. For the time being, when there is a duplicate  due to songs with the same id, the duplicates will be removed and the same song will be added at the end of the playlist. This means that the original position of the duplicated song in the playlist won't be maintained.

**Comment by alfaplays** [comment]
@JMPerez I had the same exact problem yesterday. I tried the page again and it is working now, indeed, all the songs get reinserted at the end of the playlist.

**Comment by JMPerez** [comment]
Yes, it’s a short term trade-off while I check that the songs can be added
at any position, and I calculate the final position after all the deletions.

I wanted to prioritize a fix first and then eventually work on the right
position.

**Comment by brrusselburg** [comment]
Sorry for the delay! But yes, it works as expected now. Thanks for the quick fix!

**Comment by JMPerez** [comment]
Thanks, @brrusselburg! I'm closing this task.
