### ISSUE TITLE
deleting songs that are not dupes

### ISSUE THREAD

**Issue by pablormsn** [JMPerez/spotify-dedup#163]
I have noticed that in some playlists, when i pressed delete, the number of songs of the playlist decreased but the dupes were still there. I tried again and the same happened. 

Testing, I noticed that, for some reason, the songs that got deleted were the ones that were just above of the dupes ones. I dont know why did this happen, maybe it has to be with podcasts or spotify-deleted songs? 

Also, is there a way to recover deleted songs from a playlists? Because now i dont have a clue of the songs that got deleted, and I would want them back

**Comment by JMPerez** [comment]
@pablormsn Can you provide an example of a playlist where you see this behaviour?

**Comment by pablormsn** [comment]
Sure:

https://open.spotify.com/playlist/4ENdP6Npy43E64yg7XiBrl?si=2588d12174ec4c45

Dedup says that this playlist has two dupes, and when i click delete, two songs get deleted, but no the dupes one.

Curious that I duplicated that playlist and it did delete the dupes correctly in this one, but not in the original.

**Comment by pablormsn** [comment]
It deleted the songs just above/below of the dupes ones

**Comment by JMPerez** [comment]
@pablormsn I have checked that playlist and it doesn't seem to have any duplicates.

**Comment by pablormsn** [comment]
Yeah, my bad, I totally forgot and I deleted the dupes manually :(

**Comment by JMPerez** [comment]
No worries!

I’m going to close this issue as it can’t be reproduced. Also, there are many users using Dedup every day to remove duplicates and if this was a generally spread problem it would have been brought up many times.

Feel free to reopen it if you see this problem again.
