### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by idohdq** [JMPerez/spotify-dedup#164]
I try to log into Spotify dedup, but when I do, it gets stuck at https://spotify-dedup.com/callback#access_token=BQAf5zCtH_4QX0S4rbodQlKZBQWvtFlvq2WPcj89rFP8OSCE4H6wNNDqb2lY3eSbgTfJxfg49tYjrPjjfQUcdtP0KnnJfRhciIfkLeSVXGR-RIkAuO5-WT0Lnq0dkYBGfhPkTDTxUCJKi2EUfDXrdwq2uvYZ4HJvOhuXVtG51VdKvkT93yoFGynWMQX5juSrka17zJ034i8cq3UFF_8DrPcnNv5PAcEs3fFVvz0Z0ev7aYtF0Gc_McX2pdzDzkZcBXobAsVUyZU&token_type=Bearer&expires_in=3600 and I get an about:blank screen.

**Comment by char1eslu** [comment]
me too

**Comment by BobWs** [comment]
same here!

**Comment by JMPerez** [comment]
Please, try again. I have reworked the login logic to solve some issues in certain browsers and it should now be working fine. Otherwise feel free to reopen and indicate what browser and operating system you were using when you encountered the issue.
