### ISSUE TITLE
Not removing duplicated from liked songs

### ISSUE THREAD

**Issue by animagus12** [JMPerez/spotify-dedup#167]
Spotify API changes, duplicates are not getting removed from liked songs, stills works on normal playlists.

**Comment by JMPerez** [comment]
Can you provide as specific examples of songs in your likes songs list that
are not getting deduplicated?

**Comment by animagus12** [comment]
![image](https://github.com/user-attachments/assets/dca7b189-45c7-46c6-82f3-1b3305d75a0b)

**Comment by dvvmvp** [comment]
I've got the same issue on my end. I clicked "remove duplicates from your liked songs" but that didn't do anything as both songs are still in the liked songs playlist...

![image](https://github.com/user-attachments/assets/191ac15b-11e9-44b8-ab5d-cc3ff8a39739)

**Comment by gustavobosch** [comment]
Same problem here. Could we have a fix?

**Comment by Arthaey** [comment]
I have the same problem as well.

**Comment by JMPerez** [comment]
I have just fixed the issue on https://github.com/JMPerez/spotify-dedup/commit/7d4817acd34a758a569a48e8e77977a223d555b6

Please, try again @Arthaey, @gustavobosch, @dvvmvp, @animagus12

**Comment by dvvmvp** [comment]
It works fine now. Amazing work. Thanks a lot.

**Comment by Arthaey** [comment]
Works for me too. Thank you for the quick fix! <3
