### ISSUE TITLE
Error: Failed fetch

### ISSUE THREAD

**Issue by PieterGh** [JMPerez/spotify-dedup#168]
Any fix for this? I have 19.000 liked songs, maybe that might be the issue.
![image](https://github.com/user-attachments/assets/306f175a-66f2-4b8a-8cfb-c94915eafc1e)

**Comment by JMPerez** [comment]
Can you try again? Also, it’s impossible to troubleshoot unless you provide information about the environment in which this was running and the user name in which it was run.

I’m closing the issue since there have been many changes recently to address improvements in the retry logic.

**Comment by PieterGh** [comment]
After trying for a couple of months, last month it suddenly worked via the site. I've tried it again for you today and it still works :) So thank you!

**Comment by JMPerez** [comment]
Great to hear!!!
