### ISSUE TITLE
Does not detect duplicates in some playlists

### ISSUE THREAD

**Issue by SwooshyCueb** [JMPerez/spotify-dedup#18]
http://open.spotify.com/user/swooshycueb/playlist/04ThdPnAJFrIsEsFtogEPd
For whatever reason, the tool does not detect any dupes in this playlist. It should detect several.
For example: C'est La Vie by Eppic should be detected as a dupe via Spotify ID

**Comment by JMPerez** [comment]
Could you try again? I have lowered the amount of requests per second to prevent being rate-limited by Spotify's Web API (see https://github.com/JMPerez/spotify-dedup/commit/b6091581e3700ccbb1e5a0e26dbb59422fa3d15f).

It will take more time but hopefully it will work:

![screen shot 2017-05-08 at 21 13 40](https://cloud.githubusercontent.com/assets/416456/25820964/7881ab46-3433-11e7-939b-b7dda5a7eea8.png)
