### ISSUE TITLE
More lenient check for same name.

### ISSUE THREAD

**Issue by tkn** [JMPerez/spotify-dedup#19]
I'd like to see songs such as "In the street" and "In the street - single mix" (same artist, duration close) highlighted as potential duplicates.

**Comment by felipecustodio** [comment]
I've been having this problem lately, with songs with titles like:

| Title        | Artist          |
| ------------- |:-------------:| 
| im closing my eyes      | Shiloh | 
| im closing my eyes (Feat. shiloh)      |  potsu, Shiloh |

**Comment by JMPerez** [comment]
@tkn, @felipecustodio Could you paste a link to the tracks here? It's difficult to find out that 2 tracks if they don't have the same title and similar time. If you add a link to them here I can look into implementing some basic support for this.

**Comment by felipecustodio** [comment]
@JMPerez Sorry, I believe I got the problem wrong! 

It looks like it was a renaming issue with Spotify. The track was added some time ago to the playlist (via IFTTT), then added again recently with the new name (feat. shiloh), so I'm not finding the one I deleted (dedup didn't mark it as duplicated). 

If it happens again I'll post here so we can investigate, thanks for the answer :)

**Comment by JMPerez** [comment]
I'll close the ticket for now.
