### ISSUE TITLE
Script timeouts with stupidly large playlists

### ISSUE THREAD

**Issue by jon001** [JMPerez/spotify-dedup#21]
Thanks for a great tool - it's helping me to tame this ridiculous playlist.

I had a playlist of about 10,000 songs (lots of dupes) exported from BBC Playlister (every song I've clicked "like" on for the last few years). The tool seems to hang when processing the playlist in Edge ("the script has stopped responding / recover webpage). Seems better in Chrome (longer timeouts?) but does hang occasionally. I'm not all that surprised but thought I might as well share my experience.

Despite apparently failing the first time I used it, the tool kept processing (CPU cycles eaten, bandwidth nibbled, song count in spotify reducing).

Playlist is down to 3,749 songs now and the tool seems happier, though it says, "Your playlists have been processed! Congrats! Your playlists don't have duplicates." while it's still deleting the dupes it found.

It doesn't seem to get all of the dupes - I've run it five times now and it deletes more each time. Perhaps it was still processing when I ran again but it wasn't using CPU at that point and the total in spotify seemed stable.

[EDIT]
The list is down to 993 songs now. It was a *very* duplicated list!

[EDIT2]
@jmperezperez suggested linking to the playlist in this issue but as it's down to "normal" size now I don't think that would be useful. Happy to try something else if it would help. You could simulate the list by taking a 1000-song playlist and adding 9 copies of each track :-/

**Comment by Dovry** [comment]
I took all my playlists and dumped them into one, then ran the dedup.

had a ~5k song playlist parsed in ~15 seconds without issue, removed about 100 tracks.

**Comment by Dovry** [comment]
So I took the previously mentioned list, added multiple duplicates and ran the dedup

![screenshot_1](https://user-images.githubusercontent.com/15201298/46130058-9fd08480-c238-11e8-82d1-958e4b372815.png)

then I ran it again

![image](https://user-images.githubusercontent.com/15201298/46130139-d1e1e680-c238-11e8-9ca8-d1e63e8171a8.png)

and it works perfectly fine, took about 15 seconds

so I tested it again, this time with the same ~600 songs added again and again and again

![image](https://user-images.githubusercontent.com/15201298/46130276-2edd9c80-c239-11e8-84b0-33551ad9973b.png)

lo and behold

![image](https://user-images.githubusercontent.com/15201298/46130361-6b10fd00-c239-11e8-8b7c-98c8deb10023.png)

the playlist has the same amount of songs as the playlist I copied everything from multiple times
![image](https://user-images.githubusercontent.com/15201298/46130408-8d0a7f80-c239-11e8-850b-0acef25fcd34.png)
![image](https://user-images.githubusercontent.com/15201298/46130444-9d225f00-c239-11e8-9f11-8f484791fcd2.png)

I believe it's safe to close this issue, maybe it was your browser that couldn't handle the load?

**Comment by jon001** [comment]
Well you certainly tested this thoroughly and I agree there doesn't seem to be a problem there. I can't explain the performance in my case - it was running on a top-spec Surface Book 2 with no other significant processes running, and I tried it in both Edge and Chrome. 

But I agree - no justification to keep the issue open if it's only me who experiences any problems.

Thanks for taking the time to investigate.

**Comment by JMPerez** [comment]
Wow @Dovry!! Thank you so much for looking into this and test it thoroughly. I'm happy that the tool seems to work fine.

I'll close the ticket now.
