### ISSUE TITLE
Pennyroyal Tea by Nirvana duplication issue.

### ISSUE THREAD

**Issue by bmdisbrow** [JMPerez/spotify-dedup#58]
The app thinks the song Pennyroyal Tea by Nirvana off of their album In Utero is the same as the cover off of their MTV Unplugged album.

**Comment by JMPerez** [comment]
@bmdisbrow True. Track with id `3z53rfQOg6Eb5pBCRsd7Uu` and `6DX6W2QXiVlKYQLrQN8y83` have the same name, artists and a similar duration (218,813 s vs 220,506). The tool will consider them as duplicates, even though in this case they aren't exactly the same.

The tool accounts for a duration difference of up to 2 seconds. It doesn't process the waveform nor any other audio analysis, so a small percentage of these occurrences will happen.
