### ISSUE TITLE
Better matching by making total time fuzzy?

### ISSUE THREAD

**Issue by bengarland** [JMPerez/spotify-dedup#85]
It seems that dedup is not catching the same songs if the title and artist are the same, but the total time is slightly different by a few seconds. Is there any way to add an option to make the matching a bit more fuzzy if everything matches except the total time is different by, say, 5 seconds or less? I think this would catch most of the ones that it currently misses, while still correctly not matching on live versions, remixes, etc with the same title since those are almost always completely different running times.

Here are two example tracks that it's missing:

https://open.spotify.com/track/2xbrClBHdm2OzqnQ0jJZZM

https://open.spotify.com/track/6WxE0ZVaOAcNYOk19MMqwc

**Comment by JMPerez** [comment]
Thanks @bengarland. The threshold is set to 2 seconds or less at the moment (https://github.com/JMPerez/spotify-dedup/blob/master/dedup/deduplicator.ts#L32). It can definitely be tweaked, but it can start detecting as duplicates pairs of songs that aren't.

Will close the issue for the time being. If anyone else is coming across a similar situation, please add it to a comment below.
