### ISSUE TITLE
Bad Request - Check parameters

### ISSUE THREAD

**Issue by sadlogic** [JMPerez/spotify-dedup#9]
Hello.

I am getting this Response 400 when trying to delete duplicates from 2 of my bigger playlists with ~3500 and >7k tracks respectively. I use the online tool.
![image](https://cloud.githubusercontent.com/assets/3459808/10864216/32ef3848-7fe7-11e5-897e-a49a03666903.png)

Hope this is useful information in trying to resolve this bug.

Thanks.

PS.: I used different tools to cut duplicates now and came back to check.
It now found only 2 duplicates remaining and also couldn't remove those, so number of duplicates to remove seems to not be relevant to the bug.
I also noticed while using the other tools that i couldn't copy the whole list of tracks back to spotify, i had to chunk it up into ~500 songs at a time to avoid crashing Spotify...

**Comment by JMPerez** [comment]
Thanks for reporting, @sadlogic. If it's not a problem for you, could you paste the spotify uri of the playlist that causes the error? It would be useful to debug it since I could create one in my account with the same tracks and test against it.

**Comment by sadlogic** [comment]
That's the one: spotify:user:sadlogic:playlist:3kOgibPqwOxdRbrkIcwEjA

**Comment by JMPerez** [comment]
I have created one with the same 6,704 tracks (spotify:user:jmperezperez:playlist:6q4ALG7Anu10azwI7KeH3J) and the tool managed to run properly, since it seems it doesn't have any duplicate.

Then I added a song that was already in place and I managed to reproduce the error. I'll work in fixing it.

**Comment by sadlogic** [comment]
Oh yeah oops, i got rid of the duplicates with other tools as i said.
